### ISSUE TITLE
about environment

### ISSUE THREAD

**Issue by l-mengwei** [kornellewy/human_parse#1]
I am very happy to see your human parse repository based on pytorch. Have you run it successfully? Can I try to run it on my computer? If possible, can you tell me the operating environment of this repository? Thank you in advance, looking forward to your reply ~

**Comment by kornellewy** [comment]
1. Have you run it successfully? I run it successfully, yes, but the network does not reach the minimum of the error function. In the new version, I am using a combination of the error functions from this repository (https://github.com/hyk1996/Single-Human-Parsing-LIP), and modified the network accordingly. Soon I'll throw in the code if the network is down to a minimum.
2. Can I try to run it on my computer? Yes, take into account the number of classes. I am using my 9-class castom dataset. The dataset is made of ATR and LIP datasets. I got 1060 6gb gpu to train.
3. If possible, can you tell me the operating environment of this repository? Windows, newest Pytorch and Pytorch Lightning.

**Comment by l-mengwei** [comment]
> 1. Have you run it successfully? I run it successfully, yes, but the network does not reach the minimum of the error function. In the new version, I am using a combination of the error functions from this repository (https://github.com/hyk1996/Single-Human-Parsing-LIP), and modified the network accordingly. Soon I'll throw in the code if the network is down to a minimum.
> 2. Can I try to run it on my computer? Yes, take into account the number of classes. I am using my 9-class castom dataset. The dataset is made of ATR and LIP datasets. I got 1060 6gb gpu to train.
> 3. If possible, can you tell me the operating environment of this repository? Windows, newest Pytorch and Pytorch Lightning.

Thank you a lot ! if i want to run the repository for my datasets like CIHP datasets ，can it works？thank you take time to reply me very very much ~

**Comment by kornellewy** [comment]
for semantic segmentation - yes
for instance segmentation - i think u must mod my traning and nets

**Comment by kornellewy** [comment]
btw i can send u mod code for https://github.com/hyk1996/Single-Human-Parsing-LIP with my conv unet train. Just give my ur email.

**Comment by l-mengwei** [comment]
> btw i can send u mod code for https://github.com/hyk1996/Single-Human-Parsing-LIP with my conv unet train. Just give my ur email.

my email  3103083279@qq.com
I want to run my own pictures on CIHP-PGN, but the parsing of the CIHP dataset in the official repository is only given to test.py, and there is no datasets preprocessing process. Datasets preprocessing requires files such as edges and labels . Have you tried running the CIHP-PGN repository? Have you encountered the same problem? Have you parsed your own pictures on the CIHP-PGN repo? How did you handle the datasets preprocessing part?
I'm sorry to bother you many times, and thank you very much for your patient reply.
Wish you all the best!
